"""Static core definitions for scene graph, actions, states, and rules."""

from .actions import ACTION_SPECS, ActionSpec, ActionType, action_spec
from .action_schemas import ACTION_SCHEMAS, ActionContext, ActionSchema, apply_action_schema, validate_action_schema
from .domain_rules import APPLIANCE_CYCLE_STEPS, DRYING_RACK_STEPS, DUMP_RULES, TRASHABLE_SEMANTICS
from .edges import EdgeCategory, EdgeType, SpatialRelation
from .nodes import (
    CONTROL_OBJECT_TYPES,
    ControlObject,
    FixedObject,
    Floor,
    Human,
    MovableObject,
    Node,
    NodeType,
    Robot,
    Room,
    node_type_from_legacy,
)
from .assets.npc_library import (
    DEFAULT_ROLE,
    HOME_NPC_LIBRARY,
    HOSPITAL_NPC_LIBRARY,
    NPC_EVENT_LIBRARY,
    ROLE_SCHEDULES,
    EventEffect,
    EventPrecondition,
    EventSpec,
    ScheduleEntry,
    get_default_npcs,
    get_event_spec,
    planned_activity,
    schedule_for_role,
)
from .assets.object_library import (
    Capability,
    OBJECT_LIBRARY,
    ObjectTemplate,
    build_object_node,
    get_object_spec,
    get_object_template,
    get_objects_for_room,
    list_available_objects,
    list_object_types,
)
from .assets.object_model import (
    ObjectFamily,
    ObjectFamilySpec,
    PlacementSpec,
    SystemDependency,
    SystemSpec,
    SystemLayer,
    SystemStatus,
    SYSTEM_REGISTRY,
    system_spec,
)
from .assets.object_priors import ObjectPrior, get_object_prior, load_object_priors
from .assets.object_catalog import CatalogDisposition, CatalogResolution, resolve_catalog_label
from .scenegraph import SceneGraph
from .states import (
    DISCRETE_STATE_SPACE,
    DiscreteState,
    StateCategory,
    StateDefinition,
    StateValueType,
    STATE_DEFINITIONS,
    state_definition,
    state_table_for_object,
)
from .timed_transitions import apply_timed_transitions

__all__ = [
    "ACTION_SPECS",
    "ACTION_SCHEMAS",
    "APPLIANCE_CYCLE_STEPS",
    "ActionContext",
    "ActionSchema",
    "ActionSpec",
    "ActionType",
    "CONTROL_OBJECT_TYPES",
    "Capability",
    "ControlObject",
    "DEFAULT_ROLE",
    "DISCRETE_STATE_SPACE",
    "DRYING_RACK_STEPS",
    "DiscreteState",
    "StateCategory",
    "StateDefinition",
    "StateValueType",
    "STATE_DEFINITIONS",
    "state_definition",
    "state_table_for_object",
    "DUMP_RULES",
    "EdgeCategory",
    "EdgeType",
    "EventEffect",
    "EventPrecondition",
    "EventSpec",
    "FixedObject",
    "Floor",
    "HOME_NPC_LIBRARY",
    "HOSPITAL_NPC_LIBRARY",
    "Human",
    "MovableObject",
    "NPC_EVENT_LIBRARY",
    "Node",
    "NodeType",
    "OBJECT_LIBRARY",
    "ObjectTemplate",
    "ObjectFamily",
    "ObjectFamilySpec",
    "ObjectPrior",
    "CatalogDisposition",
    "CatalogResolution",
    "PlacementSpec",
    "ROLE_SCHEDULES",
    "SceneGraph",
    "ScheduleEntry",
    "SpatialRelation",
    "SystemDependency",
    "SystemSpec",
    "SystemLayer",
    "SystemStatus",
    "SYSTEM_REGISTRY",
    "system_spec",
    "TRASHABLE_SEMANTICS",
    "action_spec",
    "apply_action_schema",
    "apply_timed_transitions",
    "build_object_node",
    "get_default_npcs",
    "get_event_spec",
    "get_object_spec",
    "get_object_prior",
    "get_object_template",
    "get_objects_for_room",
    "list_available_objects",
    "list_object_types",
    "load_object_priors",
    "resolve_catalog_label",
    "node_type_from_legacy",
    "planned_activity",
    "schedule_for_role",
    "validate_action_schema",
]
